# Generated by Django 2.1.7 on 2019-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0004_auto_20190401_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document',
            field=models.FileField(default=' ', upload_to='documents/'),
        ),
    ]
