# Generated by Django 2.1.7 on 2019-04-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0006_auto_20190401_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
