# Generated by Django 2.1.7 on 2019-04-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0007_auto_20190401_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='document',
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
