# Generated by Django 2.1.7 on 2019-04-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0009_person_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
